<?php

namespace Database\Factories;

use App\Models\Literature;
use App\Enums\LiteratureType;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Literature>
 */
class LiteratureFactory extends Factory
{
    protected $model = Literature::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'code' => null, // Generated by observer if null
            'short_ref' => $this->faker->lastName() . ' et al., ' . $this->faker->year(),
            'full_ref' => $this->faker->sentence(10),
            'type' => $this->faker->randomElement(LiteratureType::cases()),
            'doi' => $this->faker->optional()->numerify('10.####/####'),
            'link' => $this->faker->optional()->url(),
        ];
    }
}
